
server:
  port: 8080

mybatis:
  mapperLocations: classpath:com/simba/fitmanager/mapping/*.xml
#  typeAliasesPackage: com.simba.fitmanager.dao

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/simba?useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
            mode: LEGACYHTML5
            cache: false

jwt:
    header: Authorization
    secret: mySecret
    expiration: 10
    tokenHead: Bearer
    route:
        authentication.path: auth/login
        authentication.refresh: auth/refresh
        authentication.register: "auth/register"


